/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as SettingsProfileImport } from './routes/settings.profile'
import { Route as ChatsConversationIdImport } from './routes/chats/$conversationId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SettingsProfileRoute = SettingsProfileImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => rootRoute,
} as any)

const ChatsConversationIdRoute = ChatsConversationIdImport.update({
  id: '/chats/$conversationId',
  path: '/chats/$conversationId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/chats/$conversationId': {
      id: '/chats/$conversationId'
      path: '/chats/$conversationId'
      fullPath: '/chats/$conversationId'
      preLoaderRoute: typeof ChatsConversationIdImport
      parentRoute: typeof rootRoute
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chats/$conversationId': typeof ChatsConversationIdRoute
  '/settings/profile': typeof SettingsProfileRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chats/$conversationId': typeof ChatsConversationIdRoute
  '/settings/profile': typeof SettingsProfileRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/chats/$conversationId': typeof ChatsConversationIdRoute
  '/settings/profile': typeof SettingsProfileRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/chats/$conversationId' | '/settings/profile'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/chats/$conversationId' | '/settings/profile'
  id: '__root__' | '/' | '/chats/$conversationId' | '/settings/profile'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatsConversationIdRoute: typeof ChatsConversationIdRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatsConversationIdRoute: ChatsConversationIdRoute,
  SettingsProfileRoute: SettingsProfileRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/chats/$conversationId",
        "/settings/profile"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/chats/$conversationId": {
      "filePath": "chats/$conversationId.tsx"
    },
    "/settings/profile": {
      "filePath": "settings.profile.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
